// Sample an existing public-domain Camino waymark, rather than invent its shape.
// Source: St. James way shell.svg, Gambo7 / Spacejam2, Wikimedia Commons.
import {readFileSync, writeFileSync} from 'node:fs';
import vm from 'node:vm';

const base = new URL('../', import.meta.url);
const source = readFileSync(new URL('data/pilgrim-shell.svg', base), 'utf8');
const path = [...source.matchAll(/<path\b[\s\S]*?\/>/g)]
  .map(match => match[0]).find(tag => /id="path3049"/.test(tag));
const d = path?.match(/\bd="([^"]+)"/)?.[1];
if (!d) throw new Error('The source shell path is missing.');

// This source uses only one relative move, relative cubics, and a close.
// Fail clearly if the source changes instead of silently misreading a command.
const tokens = d.match(/[a-df-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:e[-+]?\d+)?/gi);
const outline = [];
let cursor = 0, command, current = [0, 0], start;
const point = () => {
  const pair = tokens.slice(cursor, cursor + 2).map(Number);
  if (pair.length !== 2 || !pair.every(Number.isFinite)) throw new Error('Invalid shell path coordinates.');
  cursor += 2;
  return pair;
};
const midpoint = (a, b) => [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
const distance = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]);
function flatten(a, b, c, end, depth = 0) {
  // Adaptive subdivision preserves the actual curved ribs and rounded hinge.
  if (depth >= 12 || distance(a, b) + distance(b, c) + distance(c, end) - distance(a, end) < .015) {
    outline.push(end);
    return;
  }
  const ab = midpoint(a, b), bc = midpoint(b, c), ce = midpoint(c, end);
  const abc = midpoint(ab, bc), bce = midpoint(bc, ce), center = midpoint(abc, bce);
  flatten(a, ab, abc, center, depth + 1);
  flatten(center, bce, ce, end, depth + 1);
}
while (cursor < tokens.length) {
  if (/^[a-z]$/i.test(tokens[cursor])) command = tokens[cursor++];
  if (command === 'm') {
    if (start) throw new Error('Expected a single closed source contour.');
    current = point();
    start = current;
    outline.push(current);
    command = null;
  } else if (command === 'c') {
    const relative = () => point().map((value, axis) => value + current[axis]);
    const b = relative(), c = relative(), end = relative();
    flatten(current, b, c, end);
    current = end;
  } else if (command === 'z') {
    outline.push(start);
    command = null;
  } else {
    throw new Error(`Unsupported shell path command: ${command}`);
  }
}
if (outline.at(-1) !== start) throw new Error('The shell contour must close.');

const sandbox = {window: {}};
vm.runInNewContext(readFileSync(new URL('assets/math-network.js', base), 'utf8'), sandbox);
const spain = sandbox.window.personalSiteMathNetwork;
const width = 800, height = 900, count = spain.nodes.length;
// Normalize using the original upright bounds to preserve its displayed size.
// The blue sign rectangle is deliberately not part of the particle artwork.
const upright = outline.map(([x, y]) => [y, 310 - x]);
const xs = upright.map(p => p[0]), ys = upright.map(p => p[1]);
const bounds = {left: Math.min(...xs), right: Math.max(...xs), top: Math.min(...ys), bottom: Math.max(...ys)};
const scale = Math.min((width - 90) / (bounds.right - bounds.left), (height - 80) / (bounds.bottom - bounds.top));
// Rotate 90 degrees clockwise around the artwork's center: hinge left, fan right.
const projected = upright.map(([x, y]) => {
  const centeredX = (x - (bounds.left + bounds.right) / 2) * scale;
  const centeredY = (y - (bounds.top + bounds.bottom) / 2) * scale;
  return [width / 2 - centeredY, height / 2 + centeredX];
});
const segments = projected.slice(1).map((b, i) => ({a: projected[i], b, length: distance(projected[i], b)}))
  .filter(segment => segment.length > 0);
const length = segments.reduce((sum, segment) => sum + segment.length, 0);
const nodes = [], connections = [], tangents = [];
let segment = 0, travelled = 0;
for (let i = 0; i < count; i++) {
  const along = length * i / count;
  while (segment < segments.length - 1 && travelled + segments[segment].length < along) {
    travelled += segments[segment++].length;
  }
  const {a, b, length: span} = segments[segment], t = (along - travelled) / span;
  nodes.push(a.map((value, axis) => Number((value + (b[axis] - value) * t).toFixed(3))));
  tangents.push(Math.atan2(b[1] - a[1], b[0] - a[0]));
  connections.push([i, (i + 1) % count]);
}
const vectorAngles = spain.vectors.map(vector => tangents[vector.node]);
const graph = {width, height, nodes, connections, vectorAngles};
const sourceUrl = 'https://commons.wikimedia.org/wiki/File:St._James_way_shell.svg';
const credit = 'Camino pilgrim shell adapted from St. James way shell.svg by Gambo7 / Spacejam2, Wikimedia Commons, public domain. Fan facing right, sign background omitted, and shell contour sampled into particles.';
writeFileSync(new URL('assets/shell-network.js', base), `// Generated by scripts/generate-shell.mjs.\n// ${credit}\n// ${sourceUrl}\nwindow.personalSiteSymbolNetwork = ${JSON.stringify(graph)};\n`);
const f = value => Number(value.toFixed(2));
const lines = connections.map(([i, j]) => `M${nodes[i].map(f).join(',')}L${nodes[j].map(f).join(',')}`).join('');
const dots = nodes.map(([x, y], i) => `<circle cx="${f(x)}" cy="${f(y)}" r="${i % 11 === 0 ? 1.7 : .95}"/>`).join('');
writeFileSync(new URL('assets/shell-network.svg', base), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" fill="none">
<title>Santiago de Compostela pilgrim's shell</title>
<desc>The Camino scallop-shell symbol, its fan and radiating ribs traced with particles. ${credit} Source: ${sourceUrl}</desc>
<path d="${lines}" stroke="#647a8b" stroke-width=".7" opacity=".4"/>
<g fill="#647a8b" opacity=".5">${dots}</g>
</svg>\n`);
console.log(`Generated Camino pilgrim shell: ${nodes.length} particles and ${connections.length} connections, sampled from the public-domain waymark.`);
